import Link from 'next/link'
import Head from 'next/head'

import { Container, Main, Title, Description } from '../components/sharedstyles'
import { DualPanelLayout } from '../components/Layout/DualPanelLayout'
import Cards from '../components/cards/cards'

export default function Home() {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <DualPanelLayout
          leftPanel={
            <>
               <Title>About Page</Title>
        <Description>
          <Link href="/">&larr; Go Back</Link>
        </Description>
            </>
          }
          rightPanel={
            <>
                <Title>About Page</Title>
                
              <Cards />
            </>
          } />
      </Main>
    </Container>
  )
}
